/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/ui/Footer.vue')['default']
    GameCard: typeof import('./src/components/ui/GameCard.vue')['default']
    Header: typeof import('./src/components/ui/Header.vue')['default']
    Info: typeof import('./src/components/ui/Info.vue')['default']
    IsLoading: typeof import('./src/components/ui/IsLoading.vue')['default']
    IsLoadingBalls: typeof import('./src/components/ui/IsLoadingBalls.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubscribeForm: typeof import('./src/components/ui/SubscribeForm.vue')['default']
  }
}
