/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutGame: typeof import('./src/components/ui/card/AboutGame.vue')['default']
    DetailsCard: typeof import('./src/components/ui/card/DetailsCard.vue')['default']
    Footer: typeof import('./src/components/ui/Footer.vue')['default']
    GameCardFoter: typeof import('./src/components/ui/card/GameCardFoter.vue')['default']
    Header: typeof import('./src/components/ui/Header.vue')['default']
    IconCheck: typeof import('./src/components/ui/card/IconCheck.vue')['default']
    Info: typeof import('./src/components/ui/Info.vue')['default']
    InfoGameCard: typeof import('./src/components/ui/card/InfoGameCard.vue')['default']
    IsLoading: typeof import('./src/components/ui/IsLoading.vue')['default']
    IsLoadingBalls: typeof import('./src/components/ui/IsLoadingBalls.vue')['default']
    MenuNav: typeof import('./src/components/ui/navigation/MenuNav.vue')['default']
    PopupRedirect: typeof import('./src/components/ui/popup-redirect/PopupRedirect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsCard: typeof import('./src/components/ui/card/StatsCard.vue')['default']
    SubscribeForm: typeof import('./src/components/ui/SubscribeForm.vue')['default']
    SubscribeGameCard: typeof import('./src/components/ui/card/SubscribeGameCard.vue')['default']
    TutorialCard: typeof import('./src/components/ui/card/TutorialCard.vue')['default']
  }
}
